basic:basic.vala
	valac --pkg gtk+-3.0 basic.vala
sync:sync.vala
	valac --pkg gtk+-3.0 sync.vala
textViewer:textViewer.vala
	valac --pkg gtk+-3.0 textViewer.vala
dialog:dialog.vala
	valac --pkg gtk+-3.0 dialog.vala
treeView:treeView.vala
	valac --pkg gtk+-3.0 treeView.vala
filemanager:filemanager.vala
	valac --pkg gtk+-3.0 filemanager.vala
iconview:iconview.vala
	valac --pkg gtk+-3.0 $<
clean:
	rm -f basic sync textViewer treeView filemanager