/* shaped-window.c generated by valac 0.26.2, the Vala compiler
 * generated from shaped-window.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <cairo.h>
#include <gdk/gdk.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_CAIRO_SHAPED (cairo_shaped_get_type ())
#define CAIRO_SHAPED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CAIRO_SHAPED, CairoShaped))
#define CAIRO_SHAPED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CAIRO_SHAPED, CairoShapedClass))
#define IS_CAIRO_SHAPED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CAIRO_SHAPED))
#define IS_CAIRO_SHAPED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CAIRO_SHAPED))
#define CAIRO_SHAPED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CAIRO_SHAPED, CairoShapedClass))

typedef struct _CairoShaped CairoShaped;
typedef struct _CairoShapedClass CairoShapedClass;
typedef struct _CairoShapedPrivate CairoShapedPrivate;
#define _cairo_pattern_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_pattern_destroy (var), NULL)))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _cairo_region_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_region_destroy (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _CairoShaped {
	GtkWindow parent_instance;
	CairoShapedPrivate * priv;
};

struct _CairoShapedClass {
	GtkWindowClass parent_class;
};

struct _CairoShapedPrivate {
	gboolean inside;
	gdouble cur_x;
	gdouble cur_y;
	gboolean size_valid;
	gboolean pos_valid;
	cairo_pattern_t* grad_in;
	cairo_pattern_t* grad_out;
	cairo_surface_t* event_mask;
	gint highlighted;
	gboolean* off_light;
	gint off_light_length1;
	gint _off_light_size_;
	gdouble* hour_x;
	gint hour_x_length1;
	gint _hour_x_size_;
	gdouble* hour_y;
	gint hour_y_length1;
	gint _hour_y_size_;
	gdouble radius;
};

struct _Block1Data {
	int _ref_count_;
	CairoShaped* cairo_sample;
};


static gpointer cairo_shaped_parent_class = NULL;

GType cairo_shaped_get_type (void) G_GNUC_CONST;
#define CAIRO_SHAPED_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CAIRO_SHAPED, CairoShapedPrivate))
enum  {
	CAIRO_SHAPED_DUMMY_PROPERTY
};
CairoShaped* cairo_shaped_new (void);
CairoShaped* cairo_shaped_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
gboolean cairo_shaped_mouse_entered (CairoShaped* self, GdkEventCrossing* e);
static gboolean _cairo_shaped_mouse_entered_gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
gboolean cairo_shaped_mouse_left (CairoShaped* self, GdkEventCrossing* e);
static gboolean _cairo_shaped_mouse_left_gtk_widget_leave_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
gboolean cairo_shaped_button_pressed (CairoShaped* self, GdkEventButton* e);
static gboolean _cairo_shaped_button_pressed_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
gboolean cairo_shaped_scrolled (CairoShaped* self, GdkEventScroll* e);
static gboolean _cairo_shaped_scrolled_gtk_widget_scroll_event (GtkWidget* _sender, GdkEventScroll* event, gpointer self);
static gboolean cairo_shaped_on_expose (CairoShaped* self, cairo_t* ctx);
static gboolean _cairo_shaped_on_expose_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self);
static void cairo_shaped_create_gradients (CairoShaped* self);
static gdouble cairo_shaped_c (CairoShaped* self, gint val);
static void cairo_shaped_create_mask (CairoShaped* self);
static void cairo_shaped_locate_dots (CairoShaped* self);
static void cairo_shaped_find_highlight (CairoShaped* self);
static gint cairo_shaped_main (gchar** args, int args_length1);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean __lambda4_ (Block1Data* _data1_);
static gboolean ___lambda4__gsource_func (gpointer self);
static void cairo_shaped_finalize (GObject* obj);


/**
         * Just creating the window, setting things up
         **/
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


static gboolean _cairo_shaped_mouse_entered_gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = cairo_shaped_mouse_entered ((CairoShaped*) self, event);
	return result;
}


static gboolean _cairo_shaped_mouse_left_gtk_widget_leave_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = cairo_shaped_mouse_left ((CairoShaped*) self, event);
	return result;
}


static gboolean _cairo_shaped_button_pressed_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = cairo_shaped_button_pressed ((CairoShaped*) self, event);
	return result;
}


static gboolean _cairo_shaped_scrolled_gtk_widget_scroll_event (GtkWidget* _sender, GdkEventScroll* event, gpointer self) {
	gboolean result;
	result = cairo_shaped_scrolled ((CairoShaped*) self, event);
	return result;
}


static gboolean _cairo_shaped_on_expose_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self) {
	gboolean result;
	result = cairo_shaped_on_expose ((CairoShaped*) self, cr);
	return result;
}


CairoShaped* cairo_shaped_construct (GType object_type) {
	CairoShaped * self = NULL;
	gdouble* _tmp0_ = NULL;
	gdouble* _tmp1_ = NULL;
	gboolean* _tmp2_ = NULL;
	GdkScreen* _tmp10_ = NULL;
	GdkScreen* _tmp11_ = NULL;
	GdkVisual* _tmp12_ = NULL;
	self = (CairoShaped*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "Cairo Vala Demo");
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_default_size ((GtkWindow*) self, 200, 200);
	gtk_window_set_keep_above ((GtkWindow*) self, TRUE);
	self->priv->inside = FALSE;
	self->priv->size_valid = FALSE;
	self->priv->pos_valid = FALSE;
	_tmp0_ = g_new0 (gdouble, 12);
	self->priv->hour_x = (g_free (self->priv->hour_x), NULL);
	self->priv->hour_x = _tmp0_;
	self->priv->hour_x_length1 = 12;
	self->priv->_hour_x_size_ = self->priv->hour_x_length1;
	_tmp1_ = g_new0 (gdouble, 12);
	self->priv->hour_y = (g_free (self->priv->hour_y), NULL);
	self->priv->hour_y = _tmp1_;
	self->priv->hour_y_length1 = 12;
	self->priv->_hour_y_size_ = self->priv->hour_y_length1;
	self->priv->highlighted = -1;
	_tmp2_ = g_new0 (gboolean, 12);
	self->priv->off_light = (g_free (self->priv->off_light), NULL);
	self->priv->off_light = _tmp2_;
	self->priv->off_light_length1 = 12;
	self->priv->_off_light_size_ = self->priv->off_light_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gint _tmp5_ = 0;
				gboolean* _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				gboolean* _tmp7_ = NULL;
				gint _tmp7__length1 = 0;
				gint _tmp8_ = 0;
				gboolean _tmp9_ = FALSE;
				if (!_tmp3_) {
					gint _tmp4_ = 0;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = i;
				_tmp6_ = self->priv->off_light;
				_tmp6__length1 = self->priv->off_light_length1;
				if (!(_tmp5_ < _tmp6__length1)) {
					break;
				}
				_tmp7_ = self->priv->off_light;
				_tmp7__length1 = self->priv->off_light_length1;
				_tmp8_ = i;
				_tmp7_[_tmp8_] = FALSE;
				_tmp9_ = _tmp7_[_tmp8_];
			}
		}
	}
	gtk_widget_add_events ((GtkWidget*) self, (gint) GDK_BUTTON_PRESS_MASK);
	gtk_widget_add_events ((GtkWidget*) self, (gint) GDK_ENTER_NOTIFY_MASK);
	gtk_widget_add_events ((GtkWidget*) self, (gint) GDK_LEAVE_NOTIFY_MASK);
	gtk_widget_add_events ((GtkWidget*) self, (gint) GDK_SCROLL_MASK);
	g_signal_connect_object ((GtkWidget*) self, "enter-notify-event", (GCallback) _cairo_shaped_mouse_entered_gtk_widget_enter_notify_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "leave-notify-event", (GCallback) _cairo_shaped_mouse_left_gtk_widget_leave_notify_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "button-press-event", (GCallback) _cairo_shaped_button_pressed_gtk_widget_button_press_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "scroll-event", (GCallback) _cairo_shaped_scrolled_gtk_widget_scroll_event, self, 0);
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
	gtk_widget_set_app_paintable ((GtkWidget*) self, TRUE);
	_tmp10_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp11_ = _tmp10_;
	_tmp12_ = gdk_screen_get_rgba_visual (_tmp11_);
	gtk_widget_set_visual ((GtkWidget*) self, _tmp12_);
	g_signal_connect_object ((GtkWidget*) self, "draw", (GCallback) _cairo_shaped_on_expose_gtk_widget_draw, self, 0);
	return self;
}


CairoShaped* cairo_shaped_new (void) {
	return cairo_shaped_construct (TYPE_CAIRO_SHAPED);
}


gboolean cairo_shaped_mouse_entered (CairoShaped* self, GdkEventCrossing* e) {
	gboolean result = FALSE;
	GdkEventCrossing* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GdkEventCrossing* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (e != NULL, FALSE);
	_tmp0_ = e;
	_tmp1_ = _tmp0_->x;
	self->priv->cur_x = _tmp1_;
	_tmp2_ = e;
	_tmp3_ = _tmp2_->y;
	self->priv->cur_y = _tmp3_;
	self->priv->inside = TRUE;
	self->priv->pos_valid = FALSE;
	gtk_widget_queue_draw ((GtkWidget*) self);
	result = TRUE;
	return result;
}


gboolean cairo_shaped_mouse_left (CairoShaped* self, GdkEventCrossing* e) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (e != NULL, FALSE);
	self->priv->cur_x = (gdouble) (-100);
	self->priv->cur_y = (gdouble) (-100);
	self->priv->inside = FALSE;
	self->priv->pos_valid = FALSE;
	gtk_widget_queue_draw ((GtkWidget*) self);
	result = TRUE;
	return result;
}


gboolean cairo_shaped_button_pressed (CairoShaped* self, GdkEventButton* e) {
	gboolean result = FALSE;
	GdkEventButton* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (e != NULL, FALSE);
	_tmp0_ = e;
	_tmp1_ = _tmp0_->button;
	if (_tmp1_ == ((guint) 2)) {
		gtk_widget_destroy ((GtkWidget*) self);
	} else {
		gint _tmp2_ = 0;
		GdkEventButton* _tmp9_ = NULL;
		guint _tmp10_ = 0U;
		GdkEventButton* _tmp11_ = NULL;
		gdouble _tmp12_ = 0.0;
		GdkEventButton* _tmp13_ = NULL;
		gdouble _tmp14_ = 0.0;
		GdkEventButton* _tmp15_ = NULL;
		guint32 _tmp16_ = 0U;
		_tmp2_ = self->priv->highlighted;
		if (_tmp2_ >= 0) {
			gboolean* _tmp3_ = NULL;
			gint _tmp3__length1 = 0;
			gint _tmp4_ = 0;
			gboolean* _tmp5_ = NULL;
			gint _tmp5__length1 = 0;
			gint _tmp6_ = 0;
			gboolean _tmp7_ = FALSE;
			gboolean _tmp8_ = FALSE;
			_tmp3_ = self->priv->off_light;
			_tmp3__length1 = self->priv->off_light_length1;
			_tmp4_ = self->priv->highlighted;
			_tmp5_ = self->priv->off_light;
			_tmp5__length1 = self->priv->off_light_length1;
			_tmp6_ = self->priv->highlighted;
			_tmp7_ = _tmp5_[_tmp6_];
			_tmp3_[_tmp4_] = !_tmp7_;
			_tmp8_ = _tmp3_[_tmp4_];
		}
		_tmp9_ = e;
		_tmp10_ = _tmp9_->button;
		_tmp11_ = e;
		_tmp12_ = _tmp11_->x_root;
		_tmp13_ = e;
		_tmp14_ = _tmp13_->y_root;
		_tmp15_ = e;
		_tmp16_ = _tmp15_->time;
		gtk_window_begin_move_drag ((GtkWindow*) self, (gint) _tmp10_, (gint) _tmp12_, (gint) _tmp14_, _tmp16_);
	}
	result = TRUE;
	return result;
}


gboolean cairo_shaped_scrolled (CairoShaped* self, GdkEventScroll* e) {
	gboolean result = FALSE;
	gint width = 0;
	gint height = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint x = 0;
	gint y = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	GdkEventScroll* _tmp4_ = NULL;
	GdkScrollDirection _tmp5_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (e != NULL, FALSE);
	gtk_window_get_size ((GtkWindow*) self, &_tmp0_, &_tmp1_);
	width = _tmp0_;
	height = _tmp1_;
	gtk_window_get_position ((GtkWindow*) self, &_tmp2_, &_tmp3_);
	x = _tmp2_;
	y = _tmp3_;
	_tmp4_ = e;
	_tmp5_ = _tmp4_->direction;
	if (_tmp5_ == GDK_SCROLL_UP) {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		_tmp6_ = width;
		_tmp7_ = height;
		gtk_window_resize ((GtkWindow*) self, _tmp6_ + 4, _tmp7_ + 4);
		_tmp8_ = x;
		_tmp9_ = y;
		gtk_window_move ((GtkWindow*) self, _tmp8_ - 2, _tmp9_ - 2);
		self->priv->size_valid = FALSE;
		gtk_widget_queue_draw ((GtkWidget*) self);
	} else {
		GdkEventScroll* _tmp10_ = NULL;
		GdkScrollDirection _tmp11_ = 0;
		_tmp10_ = e;
		_tmp11_ = _tmp10_->direction;
		if (_tmp11_ == GDK_SCROLL_DOWN) {
			gint _tmp12_ = 0;
			gint _tmp13_ = 0;
			gint _tmp14_ = 0;
			gint _tmp15_ = 0;
			_tmp12_ = width;
			_tmp13_ = height;
			gtk_window_resize ((GtkWindow*) self, _tmp12_ - 4, _tmp13_ - 4);
			_tmp14_ = x;
			_tmp15_ = y;
			gtk_window_move ((GtkWindow*) self, _tmp14_ + 2, _tmp15_ + 2);
			self->priv->size_valid = FALSE;
			gtk_widget_queue_draw ((GtkWidget*) self);
		}
	}
	result = TRUE;
	return result;
}


static void cairo_shaped_create_gradients (CairoShaped* self) {
	gint width = 0;
	gint height = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gdouble _tmp9_ = 0.0;
	cairo_pattern_t* _tmp10_ = NULL;
	cairo_pattern_t* _tmp11_ = NULL;
	gdouble _tmp12_ = 0.0;
	gdouble _tmp13_ = 0.0;
	gdouble _tmp14_ = 0.0;
	cairo_pattern_t* _tmp15_ = NULL;
	gdouble _tmp16_ = 0.0;
	gdouble _tmp17_ = 0.0;
	gdouble _tmp18_ = 0.0;
	cairo_pattern_t* _tmp19_ = NULL;
	gdouble _tmp20_ = 0.0;
	gdouble _tmp21_ = 0.0;
	gdouble _tmp22_ = 0.0;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	gint _tmp26_ = 0;
	gdouble _tmp27_ = 0.0;
	cairo_pattern_t* _tmp28_ = NULL;
	cairo_pattern_t* _tmp29_ = NULL;
	gdouble _tmp30_ = 0.0;
	gdouble _tmp31_ = 0.0;
	gdouble _tmp32_ = 0.0;
	cairo_pattern_t* _tmp33_ = NULL;
	gdouble _tmp34_ = 0.0;
	gdouble _tmp35_ = 0.0;
	gdouble _tmp36_ = 0.0;
	cairo_pattern_t* _tmp37_ = NULL;
	gdouble _tmp38_ = 0.0;
	gdouble _tmp39_ = 0.0;
	gdouble _tmp40_ = 0.0;
	g_return_if_fail (self != NULL);
	gtk_window_get_size ((GtkWindow*) self, &_tmp0_, &_tmp1_);
	width = _tmp0_;
	height = _tmp1_;
	_tmp2_ = width;
	width = _tmp2_ >> 1;
	_tmp3_ = height;
	height = _tmp3_ >> 1;
	_tmp4_ = width;
	self->priv->radius = (gdouble) _tmp4_;
	_tmp5_ = width;
	_tmp6_ = height;
	_tmp7_ = width;
	_tmp8_ = height;
	_tmp9_ = self->priv->radius;
	_tmp10_ = cairo_pattern_create_radial ((gdouble) _tmp5_, (gdouble) _tmp6_, (gdouble) 0, (gdouble) _tmp7_, (gdouble) _tmp8_, _tmp9_);
	_cairo_pattern_destroy0 (self->priv->grad_in);
	self->priv->grad_in = _tmp10_;
	_tmp11_ = self->priv->grad_in;
	_tmp12_ = cairo_shaped_c (self, 10);
	_tmp13_ = cairo_shaped_c (self, 190);
	_tmp14_ = cairo_shaped_c (self, 10);
	cairo_pattern_add_color_stop_rgba (_tmp11_, 0.0, _tmp12_, _tmp13_, _tmp14_, 1.0);
	_tmp15_ = self->priv->grad_in;
	_tmp16_ = cairo_shaped_c (self, 10);
	_tmp17_ = cairo_shaped_c (self, 190);
	_tmp18_ = cairo_shaped_c (self, 10);
	cairo_pattern_add_color_stop_rgba (_tmp15_, 0.8, _tmp16_, _tmp17_, _tmp18_, 0.7);
	_tmp19_ = self->priv->grad_in;
	_tmp20_ = cairo_shaped_c (self, 10);
	_tmp21_ = cairo_shaped_c (self, 190);
	_tmp22_ = cairo_shaped_c (self, 10);
	cairo_pattern_add_color_stop_rgba (_tmp19_, 1.0, _tmp20_, _tmp21_, _tmp22_, 0.5);
	_tmp23_ = width;
	_tmp24_ = height;
	_tmp25_ = width;
	_tmp26_ = height;
	_tmp27_ = self->priv->radius;
	_tmp28_ = cairo_pattern_create_radial ((gdouble) _tmp23_, (gdouble) _tmp24_, (gdouble) 0, (gdouble) _tmp25_, (gdouble) _tmp26_, _tmp27_);
	_cairo_pattern_destroy0 (self->priv->grad_out);
	self->priv->grad_out = _tmp28_;
	_tmp29_ = self->priv->grad_out;
	_tmp30_ = cairo_shaped_c (self, 10);
	_tmp31_ = cairo_shaped_c (self, 10);
	_tmp32_ = cairo_shaped_c (self, 190);
	cairo_pattern_add_color_stop_rgba (_tmp29_, 0.0, _tmp30_, _tmp31_, _tmp32_, 1.0);
	_tmp33_ = self->priv->grad_out;
	_tmp34_ = cairo_shaped_c (self, 10);
	_tmp35_ = cairo_shaped_c (self, 10);
	_tmp36_ = cairo_shaped_c (self, 190);
	cairo_pattern_add_color_stop_rgba (_tmp33_, 0.8, _tmp34_, _tmp35_, _tmp36_, 0.7);
	_tmp37_ = self->priv->grad_out;
	_tmp38_ = cairo_shaped_c (self, 10);
	_tmp39_ = cairo_shaped_c (self, 10);
	_tmp40_ = cairo_shaped_c (self, 190);
	cairo_pattern_add_color_stop_rgba (_tmp37_, 1.0, _tmp38_, _tmp39_, _tmp40_, 0.5);
}


static void cairo_shaped_create_mask (CairoShaped* self) {
	gint width = 0;
	gint height = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	cairo_surface_t* _tmp4_ = NULL;
	cairo_t* pmcr = NULL;
	cairo_surface_t* _tmp5_ = NULL;
	cairo_t* _tmp6_ = NULL;
	cairo_t* _tmp7_ = NULL;
	cairo_t* _tmp8_ = NULL;
	cairo_t* _tmp9_ = NULL;
	cairo_t* _tmp10_ = NULL;
	cairo_t* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	cairo_t* _tmp15_ = NULL;
	cairo_t* _tmp16_ = NULL;
	cairo_surface_t* _tmp30_ = NULL;
	cairo_region_t* _tmp31_ = NULL;
	cairo_region_t* _tmp32_ = NULL;
	g_return_if_fail (self != NULL);
	gtk_window_get_size ((GtkWindow*) self, &_tmp0_, &_tmp1_);
	width = _tmp0_;
	height = _tmp1_;
	_tmp2_ = width;
	_tmp3_ = height;
	_tmp4_ = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, _tmp2_, _tmp3_);
	_cairo_surface_destroy0 (self->priv->event_mask);
	self->priv->event_mask = _tmp4_;
	_tmp5_ = self->priv->event_mask;
	_tmp6_ = cairo_create (_tmp5_);
	pmcr = _tmp6_;
	_tmp7_ = pmcr;
	cairo_set_source_rgba (_tmp7_, 1.0, 1.0, 1.0, 0.0);
	_tmp8_ = pmcr;
	cairo_set_operator (_tmp8_, CAIRO_OPERATOR_SOURCE);
	_tmp9_ = pmcr;
	cairo_paint (_tmp9_);
	_tmp10_ = pmcr;
	cairo_set_source_rgba (_tmp10_, (gdouble) 0, (gdouble) 0, (gdouble) 0, (gdouble) 1);
	_tmp11_ = pmcr;
	_tmp12_ = width;
	_tmp13_ = height;
	_tmp14_ = width;
	cairo_arc (_tmp11_, (gdouble) (_tmp12_ >> 1), (gdouble) (_tmp13_ >> 1), _tmp14_ / 20.0, (gdouble) 0, 2.0 * 3.14);
	_tmp15_ = pmcr;
	cairo_fill (_tmp15_);
	_tmp16_ = pmcr;
	cairo_stroke (_tmp16_);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp17_ = FALSE;
			_tmp17_ = TRUE;
			while (TRUE) {
				gint _tmp19_ = 0;
				cairo_t* _tmp20_ = NULL;
				gdouble* _tmp21_ = NULL;
				gint _tmp21__length1 = 0;
				gint _tmp22_ = 0;
				gdouble _tmp23_ = 0.0;
				gdouble* _tmp24_ = NULL;
				gint _tmp24__length1 = 0;
				gint _tmp25_ = 0;
				gdouble _tmp26_ = 0.0;
				gint _tmp27_ = 0;
				cairo_t* _tmp28_ = NULL;
				cairo_t* _tmp29_ = NULL;
				if (!_tmp17_) {
					gint _tmp18_ = 0;
					_tmp18_ = i;
					i = _tmp18_ + 1;
				}
				_tmp17_ = FALSE;
				_tmp19_ = i;
				if (!(_tmp19_ < 12)) {
					break;
				}
				_tmp20_ = pmcr;
				_tmp21_ = self->priv->hour_x;
				_tmp21__length1 = self->priv->hour_x_length1;
				_tmp22_ = i;
				_tmp23_ = _tmp21_[_tmp22_];
				_tmp24_ = self->priv->hour_y;
				_tmp24__length1 = self->priv->hour_y_length1;
				_tmp25_ = i;
				_tmp26_ = _tmp24_[_tmp25_];
				_tmp27_ = width;
				cairo_arc (_tmp20_, _tmp23_, _tmp26_, _tmp27_ / 40.0, (gdouble) 0, 2.0 * 3.14);
				_tmp28_ = pmcr;
				cairo_fill (_tmp28_);
				_tmp29_ = pmcr;
				cairo_stroke (_tmp29_);
			}
		}
	}
	_tmp30_ = self->priv->event_mask;
	_tmp31_ = gdk_cairo_region_create_from_surface (_tmp30_);
	_tmp32_ = _tmp31_;
	gtk_widget_input_shape_combine_region ((GtkWidget*) self, _tmp32_);
	_cairo_region_destroy0 (_tmp32_);
	_cairo_destroy0 (pmcr);
}


static void cairo_shaped_locate_dots (CairoShaped* self) {
	gint width = 0;
	gint height = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	gtk_window_get_size ((GtkWindow*) self, &_tmp0_, &_tmp1_);
	width = _tmp0_;
	height = _tmp1_;
	_tmp2_ = width;
	width = _tmp2_ >> 1;
	_tmp3_ = height;
	height = _tmp3_ >> 1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp4_ = FALSE;
			_tmp4_ = TRUE;
			while (TRUE) {
				gint _tmp6_ = 0;
				gdouble* _tmp7_ = NULL;
				gint _tmp7__length1 = 0;
				gint _tmp8_ = 0;
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				gint _tmp11_ = 0;
				gdouble _tmp12_ = 0.0;
				gdouble _tmp13_ = 0.0;
				gdouble* _tmp14_ = NULL;
				gint _tmp14__length1 = 0;
				gint _tmp15_ = 0;
				gint _tmp16_ = 0;
				gint _tmp17_ = 0;
				gint _tmp18_ = 0;
				gdouble _tmp19_ = 0.0;
				gdouble _tmp20_ = 0.0;
				if (!_tmp4_) {
					gint _tmp5_ = 0;
					_tmp5_ = i;
					i = _tmp5_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp6_ = i;
				if (!(_tmp6_ < 12)) {
					break;
				}
				_tmp7_ = self->priv->hour_x;
				_tmp7__length1 = self->priv->hour_x_length1;
				_tmp8_ = i;
				_tmp9_ = width;
				_tmp10_ = width;
				_tmp11_ = i;
				_tmp12_ = cos ((2.0 * 3.14) * (_tmp11_ / 12.0));
				_tmp7_[_tmp8_] = _tmp9_ + ((0.9 * _tmp10_) * _tmp12_);
				_tmp13_ = _tmp7_[_tmp8_];
				_tmp14_ = self->priv->hour_y;
				_tmp14__length1 = self->priv->hour_y_length1;
				_tmp15_ = i;
				_tmp16_ = height;
				_tmp17_ = height;
				_tmp18_ = i;
				_tmp19_ = sin ((2.0 * 3.14) * (_tmp18_ / 12.0));
				_tmp14_[_tmp15_] = _tmp16_ + ((0.9 * _tmp17_) * _tmp19_);
				_tmp20_ = _tmp14_[_tmp15_];
			}
		}
	}
}


static void cairo_shaped_find_highlight (CairoShaped* self) {
	gdouble rad = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->radius;
	rad = _tmp0_ / 20.0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_ = 0;
				gboolean _tmp4_ = FALSE;
				gdouble* _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				gdouble _tmp7_ = 0.0;
				gdouble _tmp8_ = 0.0;
				gdouble _tmp9_ = 0.0;
				gdouble _tmp10_ = 0.0;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				if (!(_tmp3_ < 12)) {
					break;
				}
				_tmp5_ = self->priv->hour_x;
				_tmp5__length1 = self->priv->hour_x_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = self->priv->cur_x;
				_tmp9_ = fabs (_tmp7_ - _tmp8_);
				_tmp10_ = rad;
				if (_tmp9_ <= (_tmp10_ + 2)) {
					gdouble* _tmp11_ = NULL;
					gint _tmp11__length1 = 0;
					gint _tmp12_ = 0;
					gdouble _tmp13_ = 0.0;
					gdouble _tmp14_ = 0.0;
					gdouble _tmp15_ = 0.0;
					gdouble _tmp16_ = 0.0;
					_tmp11_ = self->priv->hour_y;
					_tmp11__length1 = self->priv->hour_y_length1;
					_tmp12_ = i;
					_tmp13_ = _tmp11_[_tmp12_];
					_tmp14_ = self->priv->cur_y;
					_tmp15_ = fabs (_tmp13_ - _tmp14_);
					_tmp16_ = rad;
					_tmp4_ = _tmp15_ <= (_tmp16_ + 2);
				} else {
					_tmp4_ = FALSE;
				}
				if (_tmp4_) {
					gint _tmp17_ = 0;
					_tmp17_ = i;
					self->priv->highlighted = _tmp17_;
					return;
				}
			}
		}
	}
	self->priv->highlighted = -1;
}


/**
         * Actual drawing takes place within this method
         **/
static gpointer _cairo_pattern_reference0 (gpointer self) {
	return self ? cairo_pattern_reference (self) : NULL;
}


static void g_time_local (time_t time, struct tm* result) {
	struct tm _result_ = {0};
	struct tm _tmp0_ = {0};
	localtime_r (&time, &_tmp0_);
	_result_ = _tmp0_;
	*result = _result_;
	return;
}


static gboolean cairo_shaped_on_expose (CairoShaped* self, cairo_t* ctx) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	cairo_t* _tmp2_ = NULL;
	cairo_t* _tmp3_ = NULL;
	cairo_t* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	cairo_t* _tmp10_ = NULL;
	gdouble _tmp11_ = 0.0;
	gdouble _tmp12_ = 0.0;
	gdouble _tmp13_ = 0.0;
	cairo_t* _tmp14_ = NULL;
	cairo_t* _tmp15_ = NULL;
	gboolean _tmp16_ = FALSE;
	gdouble rad = 0.0;
	gdouble _tmp22_ = 0.0;
	cairo_t* _tmp75_ = NULL;
	gdouble _tmp76_ = 0.0;
	gdouble _tmp77_ = 0.0;
	cairo_t* _tmp78_ = NULL;
	struct tm t = {0};
	time_t _tmp79_ = 0;
	struct tm _tmp80_ = {0};
	gint hour = 0;
	struct tm _tmp81_ = {0};
	gint _tmp82_ = 0;
	gint minutes = 0;
	struct tm _tmp83_ = {0};
	gint _tmp84_ = 0;
	gint seconds = 0;
	struct tm _tmp85_ = {0};
	gint _tmp86_ = 0;
	gdouble per_hour = 0.0;
	gdouble dh = 0.0;
	gdouble _tmp87_ = 0.0;
	cairo_t* _tmp88_ = NULL;
	gdouble _tmp89_ = 0.0;
	cairo_t* _tmp90_ = NULL;
	gdouble _tmp91_ = 0.0;
	gdouble _tmp92_ = 0.0;
	gdouble _tmp93_ = 0.0;
	gdouble _tmp94_ = 0.0;
	gdouble _tmp95_ = 0.0;
	gdouble _tmp96_ = 0.0;
	cairo_t* _tmp97_ = NULL;
	gdouble _tmp98_ = 0.0;
	gdouble _tmp99_ = 0.0;
	gdouble per_minute = 0.0;
	gdouble dm = 0.0;
	gdouble _tmp100_ = 0.0;
	cairo_t* _tmp101_ = NULL;
	gdouble _tmp102_ = 0.0;
	gdouble _tmp103_ = 0.0;
	gdouble _tmp104_ = 0.0;
	gdouble _tmp105_ = 0.0;
	gdouble _tmp106_ = 0.0;
	gdouble _tmp107_ = 0.0;
	cairo_t* _tmp108_ = NULL;
	gdouble _tmp109_ = 0.0;
	gdouble _tmp110_ = 0.0;
	gdouble per_second = 0.0;
	gdouble ds = 0.0;
	gdouble _tmp111_ = 0.0;
	cairo_t* _tmp112_ = NULL;
	gdouble _tmp113_ = 0.0;
	gdouble _tmp114_ = 0.0;
	gdouble _tmp115_ = 0.0;
	gdouble _tmp116_ = 0.0;
	gdouble _tmp117_ = 0.0;
	gdouble _tmp118_ = 0.0;
	cairo_t* _tmp119_ = NULL;
	cairo_t* _tmp120_ = NULL;
	gdouble _tmp121_ = 0.0;
	gdouble _tmp122_ = 0.0;
	gdouble _tmp123_ = 0.0;
	cairo_t* _tmp124_ = NULL;
	gdouble _tmp125_ = 0.0;
	gdouble _tmp126_ = 0.0;
	gdouble _tmp127_ = 0.0;
	cairo_t* _tmp128_ = NULL;
	cairo_t* _tmp129_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (ctx != NULL, FALSE);
	_tmp0_ = self->priv->size_valid;
	if (!_tmp0_) {
		cairo_shaped_create_gradients (self);
		cairo_shaped_locate_dots (self);
		cairo_shaped_create_mask (self);
		self->priv->size_valid = TRUE;
	}
	_tmp1_ = self->priv->pos_valid;
	if (!_tmp1_) {
		cairo_shaped_find_highlight (self);
		self->priv->pos_valid = TRUE;
	}
	_tmp2_ = ctx;
	cairo_set_source_rgba (_tmp2_, 1.0, 1.0, 1.0, 0.0);
	_tmp3_ = ctx;
	cairo_set_operator (_tmp3_, CAIRO_OPERATOR_SOURCE);
	_tmp4_ = ctx;
	cairo_paint (_tmp4_);
	_tmp5_ = self->priv->inside;
	if (_tmp5_) {
		cairo_t* _tmp6_ = NULL;
		cairo_pattern_t* _tmp7_ = NULL;
		_tmp6_ = ctx;
		_tmp7_ = self->priv->grad_in;
		cairo_set_source (_tmp6_, _tmp7_);
	} else {
		cairo_t* _tmp8_ = NULL;
		cairo_pattern_t* _tmp9_ = NULL;
		_tmp8_ = ctx;
		_tmp9_ = self->priv->grad_out;
		cairo_set_source (_tmp8_, _tmp9_);
	}
	_tmp10_ = ctx;
	_tmp11_ = self->priv->radius;
	_tmp12_ = self->priv->radius;
	_tmp13_ = self->priv->radius;
	cairo_arc (_tmp10_, _tmp11_, _tmp12_, _tmp13_, (gdouble) 0, 2.0 * 3.14);
	_tmp14_ = ctx;
	cairo_fill (_tmp14_);
	_tmp15_ = ctx;
	cairo_stroke (_tmp15_);
	_tmp16_ = self->priv->inside;
	if (_tmp16_) {
		cairo_t* _tmp17_ = NULL;
		_tmp17_ = ctx;
		cairo_set_source_rgba (_tmp17_, 0.0, 0.2, 0.6, 0.8);
	} else {
		cairo_t* _tmp18_ = NULL;
		gdouble _tmp19_ = 0.0;
		gdouble _tmp20_ = 0.0;
		gdouble _tmp21_ = 0.0;
		_tmp18_ = ctx;
		_tmp19_ = cairo_shaped_c (self, 226);
		_tmp20_ = cairo_shaped_c (self, 119);
		_tmp21_ = cairo_shaped_c (self, 214);
		cairo_set_source_rgba (_tmp18_, _tmp19_, _tmp20_, _tmp21_, 0.8);
	}
	_tmp22_ = self->priv->radius;
	rad = _tmp22_ / 20.0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp23_ = FALSE;
			_tmp23_ = TRUE;
			while (TRUE) {
				gint _tmp25_ = 0;
				gdouble x = 0.0;
				gdouble* _tmp26_ = NULL;
				gint _tmp26__length1 = 0;
				gint _tmp27_ = 0;
				gdouble _tmp28_ = 0.0;
				gdouble y = 0.0;
				gdouble* _tmp29_ = NULL;
				gint _tmp29__length1 = 0;
				gint _tmp30_ = 0;
				gdouble _tmp31_ = 0.0;
				gint _tmp32_ = 0;
				gint _tmp33_ = 0;
				if (!_tmp23_) {
					gint _tmp24_ = 0;
					_tmp24_ = i;
					i = _tmp24_ + 1;
				}
				_tmp23_ = FALSE;
				_tmp25_ = i;
				if (!(_tmp25_ < 12)) {
					break;
				}
				_tmp26_ = self->priv->hour_x;
				_tmp26__length1 = self->priv->hour_x_length1;
				_tmp27_ = i;
				_tmp28_ = _tmp26_[_tmp27_];
				x = _tmp28_;
				_tmp29_ = self->priv->hour_y;
				_tmp29__length1 = self->priv->hour_y_length1;
				_tmp30_ = i;
				_tmp31_ = _tmp29_[_tmp30_];
				y = _tmp31_;
				_tmp32_ = i;
				_tmp33_ = self->priv->highlighted;
				if (_tmp32_ == _tmp33_) {
					cairo_pattern_t* s = NULL;
					cairo_t* _tmp34_ = NULL;
					cairo_pattern_t* _tmp35_ = NULL;
					cairo_pattern_t* _tmp36_ = NULL;
					cairo_t* _tmp37_ = NULL;
					gdouble _tmp38_ = 0.0;
					gdouble _tmp39_ = 0.0;
					gdouble _tmp40_ = 0.0;
					cairo_t* _tmp41_ = NULL;
					gdouble _tmp42_ = 0.0;
					gdouble _tmp43_ = 0.0;
					gdouble _tmp44_ = 0.0;
					cairo_t* _tmp45_ = NULL;
					cairo_t* _tmp46_ = NULL;
					cairo_t* _tmp47_ = NULL;
					cairo_pattern_t* _tmp48_ = NULL;
					_tmp34_ = ctx;
					_tmp35_ = cairo_get_source (_tmp34_);
					_tmp36_ = _cairo_pattern_reference0 (_tmp35_);
					s = _tmp36_;
					_tmp37_ = ctx;
					_tmp38_ = cairo_shaped_c (self, 233);
					_tmp39_ = cairo_shaped_c (self, 120);
					_tmp40_ = cairo_shaped_c (self, 20);
					cairo_set_source_rgba (_tmp37_, _tmp38_, _tmp39_, _tmp40_, 0.8);
					_tmp41_ = ctx;
					_tmp42_ = x;
					_tmp43_ = y;
					_tmp44_ = rad;
					cairo_arc (_tmp41_, _tmp42_, _tmp43_, _tmp44_, (gdouble) 0, 2.0 * 3.14);
					_tmp45_ = ctx;
					cairo_fill (_tmp45_);
					_tmp46_ = ctx;
					cairo_stroke (_tmp46_);
					_tmp47_ = ctx;
					_tmp48_ = s;
					cairo_set_source (_tmp47_, _tmp48_);
					_cairo_pattern_destroy0 (s);
				} else {
					gboolean _tmp49_ = FALSE;
					gboolean _tmp50_ = FALSE;
					_tmp50_ = self->priv->inside;
					if (!_tmp50_) {
						gboolean* _tmp51_ = NULL;
						gint _tmp51__length1 = 0;
						gint _tmp52_ = 0;
						gboolean _tmp53_ = FALSE;
						_tmp51_ = self->priv->off_light;
						_tmp51__length1 = self->priv->off_light_length1;
						_tmp52_ = i;
						_tmp53_ = _tmp51_[_tmp52_];
						_tmp49_ = _tmp53_;
					} else {
						_tmp49_ = FALSE;
					}
					if (_tmp49_) {
						cairo_pattern_t* s = NULL;
						cairo_t* _tmp54_ = NULL;
						cairo_pattern_t* _tmp55_ = NULL;
						cairo_pattern_t* _tmp56_ = NULL;
						cairo_t* _tmp57_ = NULL;
						gdouble _tmp58_ = 0.0;
						gdouble _tmp59_ = 0.0;
						gdouble _tmp60_ = 0.0;
						cairo_t* _tmp61_ = NULL;
						gdouble _tmp62_ = 0.0;
						gdouble _tmp63_ = 0.0;
						gdouble _tmp64_ = 0.0;
						cairo_t* _tmp65_ = NULL;
						cairo_t* _tmp66_ = NULL;
						cairo_t* _tmp67_ = NULL;
						cairo_pattern_t* _tmp68_ = NULL;
						_tmp54_ = ctx;
						_tmp55_ = cairo_get_source (_tmp54_);
						_tmp56_ = _cairo_pattern_reference0 (_tmp55_);
						s = _tmp56_;
						_tmp57_ = ctx;
						_tmp58_ = cairo_shaped_c (self, 216);
						_tmp59_ = cairo_shaped_c (self, 215);
						_tmp60_ = cairo_shaped_c (self, 44);
						cairo_set_source_rgba (_tmp57_, _tmp58_, _tmp59_, _tmp60_, 0.8);
						_tmp61_ = ctx;
						_tmp62_ = x;
						_tmp63_ = y;
						_tmp64_ = rad;
						cairo_arc (_tmp61_, _tmp62_, _tmp63_, _tmp64_, (gdouble) 0, 2.0 * 3.14);
						_tmp65_ = ctx;
						cairo_fill (_tmp65_);
						_tmp66_ = ctx;
						cairo_stroke (_tmp66_);
						_tmp67_ = ctx;
						_tmp68_ = s;
						cairo_set_source (_tmp67_, _tmp68_);
						_cairo_pattern_destroy0 (s);
					} else {
						cairo_t* _tmp69_ = NULL;
						gdouble _tmp70_ = 0.0;
						gdouble _tmp71_ = 0.0;
						gdouble _tmp72_ = 0.0;
						cairo_t* _tmp73_ = NULL;
						cairo_t* _tmp74_ = NULL;
						_tmp69_ = ctx;
						_tmp70_ = x;
						_tmp71_ = y;
						_tmp72_ = rad;
						cairo_arc (_tmp69_, _tmp70_, _tmp71_, _tmp72_, (gdouble) 0, 2.0 * 3.14);
						_tmp73_ = ctx;
						cairo_fill (_tmp73_);
						_tmp74_ = ctx;
						cairo_stroke (_tmp74_);
					}
				}
			}
		}
	}
	_tmp75_ = ctx;
	_tmp76_ = self->priv->radius;
	_tmp77_ = self->priv->radius;
	cairo_move_to (_tmp75_, _tmp76_, _tmp77_);
	_tmp78_ = ctx;
	cairo_set_source_rgba (_tmp78_, (gdouble) 0, (gdouble) 0, (gdouble) 0, 0.8);
	_tmp79_ = time (NULL);
	g_time_local (_tmp79_, &_tmp80_);
	t = _tmp80_;
	_tmp81_ = t;
	_tmp82_ = _tmp81_.tm_hour;
	hour = _tmp82_;
	_tmp83_ = t;
	_tmp84_ = _tmp83_.tm_min;
	minutes = _tmp84_;
	_tmp85_ = t;
	_tmp86_ = _tmp85_.tm_sec;
	seconds = _tmp86_;
	per_hour = (2 * 3.14) / 12;
	dh = (hour * per_hour) + ((per_hour / 60) * minutes);
	_tmp87_ = dh;
	dh = _tmp87_ + ((2 * 3.14) / 4);
	_tmp88_ = ctx;
	_tmp89_ = self->priv->radius;
	cairo_set_line_width (_tmp88_, 0.05 * _tmp89_);
	_tmp90_ = ctx;
	_tmp91_ = self->priv->radius;
	_tmp92_ = dh;
	_tmp93_ = cos (_tmp92_);
	_tmp94_ = self->priv->radius;
	_tmp95_ = dh;
	_tmp96_ = sin (_tmp95_);
	cairo_rel_line_to (_tmp90_, ((-0.5) * _tmp91_) * _tmp93_, ((-0.5) * _tmp94_) * _tmp96_);
	_tmp97_ = ctx;
	_tmp98_ = self->priv->radius;
	_tmp99_ = self->priv->radius;
	cairo_move_to (_tmp97_, _tmp98_, _tmp99_);
	per_minute = (2 * 3.14) / 60;
	dm = minutes * per_minute;
	_tmp100_ = dm;
	dm = _tmp100_ + ((2 * 3.14) / 4);
	_tmp101_ = ctx;
	_tmp102_ = self->priv->radius;
	_tmp103_ = dm;
	_tmp104_ = cos (_tmp103_);
	_tmp105_ = self->priv->radius;
	_tmp106_ = dm;
	_tmp107_ = sin (_tmp106_);
	cairo_rel_line_to (_tmp101_, ((-0.9) * _tmp102_) * _tmp104_, ((-0.9) * _tmp105_) * _tmp107_);
	_tmp108_ = ctx;
	_tmp109_ = self->priv->radius;
	_tmp110_ = self->priv->radius;
	cairo_move_to (_tmp108_, _tmp109_, _tmp110_);
	per_second = (2 * 3.14) / 60;
	ds = seconds * per_second;
	_tmp111_ = ds;
	ds = _tmp111_ + ((2 * 3.14) / 4);
	_tmp112_ = ctx;
	_tmp113_ = self->priv->radius;
	_tmp114_ = ds;
	_tmp115_ = cos (_tmp114_);
	_tmp116_ = self->priv->radius;
	_tmp117_ = ds;
	_tmp118_ = sin (_tmp117_);
	cairo_rel_line_to (_tmp112_, ((-0.9) * _tmp113_) * _tmp115_, ((-0.9) * _tmp116_) * _tmp118_);
	_tmp119_ = ctx;
	cairo_stroke (_tmp119_);
	_tmp120_ = ctx;
	_tmp121_ = cairo_shaped_c (self, 124);
	_tmp122_ = cairo_shaped_c (self, 32);
	_tmp123_ = cairo_shaped_c (self, 113);
	cairo_set_source_rgba (_tmp120_, _tmp121_, _tmp122_, _tmp123_, 0.7);
	_tmp124_ = ctx;
	_tmp125_ = self->priv->radius;
	_tmp126_ = self->priv->radius;
	_tmp127_ = self->priv->radius;
	cairo_arc (_tmp124_, _tmp125_, _tmp126_, 0.1 * _tmp127_, (gdouble) 0, 2.0 * 3.14);
	_tmp128_ = ctx;
	cairo_fill (_tmp128_);
	_tmp129_ = ctx;
	cairo_stroke (_tmp129_);
	result = TRUE;
	return result;
}


static gdouble cairo_shaped_c (CairoShaped* self, gint val) {
	gdouble result = 0.0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = val;
	result = _tmp0_ / 255.0;
	return result;
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_object_unref0 (_data1_->cairo_sample);
		g_slice_free (Block1Data, _data1_);
	}
}


static gboolean __lambda4_ (Block1Data* _data1_) {
	gboolean result = FALSE;
	gtk_widget_queue_draw ((GtkWidget*) _data1_->cairo_sample);
	result = TRUE;
	return result;
}


static gboolean ___lambda4__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda4_ (self);
	return result;
}


static gint cairo_shaped_main (gchar** args, int args_length1) {
	gint result = 0;
	Block1Data* _data1_;
	CairoShaped* _tmp0_ = NULL;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	gtk_init (&args_length1, &args);
	_tmp0_ = cairo_shaped_new ();
	g_object_ref_sink (_tmp0_);
	_data1_->cairo_sample = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) _data1_->cairo_sample);
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 1, ___lambda4__gsource_func, block1_data_ref (_data1_), block1_data_unref);
	gtk_main ();
	result = 0;
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return cairo_shaped_main (argv, argc);
}


static void cairo_shaped_class_init (CairoShapedClass * klass) {
	cairo_shaped_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CairoShapedPrivate));
	G_OBJECT_CLASS (klass)->finalize = cairo_shaped_finalize;
}


static void cairo_shaped_instance_init (CairoShaped * self) {
	self->priv = CAIRO_SHAPED_GET_PRIVATE (self);
}


static void cairo_shaped_finalize (GObject* obj) {
	CairoShaped * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CAIRO_SHAPED, CairoShaped);
	_cairo_pattern_destroy0 (self->priv->grad_in);
	_cairo_pattern_destroy0 (self->priv->grad_out);
	_cairo_surface_destroy0 (self->priv->event_mask);
	self->priv->off_light = (g_free (self->priv->off_light), NULL);
	self->priv->hour_x = (g_free (self->priv->hour_x), NULL);
	self->priv->hour_y = (g_free (self->priv->hour_y), NULL);
	G_OBJECT_CLASS (cairo_shaped_parent_class)->finalize (obj);
}


/**
 * This example creates a clock with the following features:
 * Shaped window -- Window is unbordered and transparent outside the clock
 * Events are only registered for the window on the hour dots or on the center dot
 * When the mouse is "in" the window (on one of the dots) it will turn green
 *    This helps you understand where the events are actually being registered
 * Clicking allows you to drag the clock.
 * There is currently no code in place to close the window, you must kill the process manually.
 * A Composited environment is required. The python code I copied this from includes checks for this.
 * In my laziness I left them out.
 **/
GType cairo_shaped_get_type (void) {
	static volatile gsize cairo_shaped_type_id__volatile = 0;
	if (g_once_init_enter (&cairo_shaped_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CairoShapedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cairo_shaped_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CairoShaped), 0, (GInstanceInitFunc) cairo_shaped_instance_init, NULL };
		GType cairo_shaped_type_id;
		cairo_shaped_type_id = g_type_register_static (gtk_window_get_type (), "CairoShaped", &g_define_type_info, 0);
		g_once_init_leave (&cairo_shaped_type_id__volatile, cairo_shaped_type_id);
	}
	return cairo_shaped_type_id__volatile;
}



